# MDB generated config template
[server]
bind-address=":8080"
mode="debug"  # GIN mode. Either debug, release or test
rollbar-token=""
rollbar-environment="development"
docs="./docs.html"

[mdb]
url="postgres://localhost/mdb?sslmode=disable&?user=postgres"

[kmedia_old]
url="postgres://localhost/kmedia_old?sslmode=disable&?user=postgres"

[test]
url-template="postgres://localhost/%s?sslmode=disable&?user=postgres"
debug-sql=false
