FORMAT: 1A
HOST: rt-dev.kbb1.com:8080

# The API for MDB

Release: <version>

## Important Info

File is identified by 3 fields:

```json
{
    "file_name": "mlt_o_rav_2017-01-04_lesson_boker_part1", 
    "created_at": 1484155956,
    "sha1": "4d4ad60c11738630178a08560362a0b2c323f87a",
}
```

Currently the only exception where those fields may be skipped is the `capture_start` command which does not have `sha1` field.

We are still (Feb 2017) not not forcing `created_at`, but will start soon (March 2017).


# Group Cmd

## /operations/capture_start

### Capture Start Handler [POST]
Starts capturing file, i.e., morning lesson or other program.

`capture_id`: Unique identifier per collection, i.e., for morning lesson all
parts of the lesson will have the same `capture_id`.


+ Request (application/json)



    + Body

            {
                "station": "10.66.1.120",
                "user": "operator@dev.com",
                "file_name": "mlt_o_rav_2017-01-04_lesson_boker_part1",
                "size": 13860980880,
                "created_at": 1484155956,
                "capture_id": "c1483491605226",
                "capture_source": "mltcap"
            }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "status": "ok"
            }
        



+ Request (application/json)



    + Body

            {
                "bad": "json"
            }        

+ Response 400 (application/json; charset=utf-8)



    + Body

            {
                "error": "Key: 'CaptureStart.Operation.Station' Error:Field validation for 'Station' failed on the 'required' tag\nKey: 'CaptureStart.Operation.User' Error:Field validation for 'User' failed on the 'required' tag\nKey: 'CaptureStart.FileName' Error:Field validation for 'FileName' failed on the 'required' tag\nKey: 'CaptureStart.CaptureID' Error:Field validation for 'CaptureID' failed on the 'required' tag\nKey: 'CaptureStart.CaptureSource' Error:Field validation for 'CaptureSource' failed on the 'required' tag",
                "status": "error"
            }
        



## /operations/capture_stop

### Capture Stop Handler [POST]
Stops capturing file, i.e., morning lesson or other program.

`capture_id`: Unique identifier per collection, i.e., for morning lesson all
parts of the lesson will have the same `capture_id`.


+ Request (application/json)



    + Body

            {
                "capture_source": "mltcap",
                "station": "10.66.1.120",
                "user": "operator@dev.com",
                "file_name": "mlt_o_rav_2017-01-04_lesson_boker_part1",
                "created_at": 1484155956,
                "size": 13860980880,
                "sha1": "4d4ad60c11738630178a08560362a0b2c323f87a",
                "part": "1",
                "capture_id": "c1483491605226"
            }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "status": "ok"
            }
        



## /operations/demux

### Demux Handler [POST]
Demux


+ Request (application/json)



    + Body

            {
                "station": "10.66.1.120",
                "user": "operator@dev.com",
                "file_name": "mlt_o_rav_2017-01-04_lesson_boker_source",
                "created_at": 1484155956,
                "sha1": "4d4ad60c11738630178a08560362a0b2c323f87a",
                "original": {
                    "file_name": "mlt_o_rav_2017-01-04_lesson_boker_orig",
                    "created_at": 1485555956,
                    "sha1": "4d4ad60c111110178a08560362a0b2c323f87a",
                    "size": 111
                },
                "proxy": {
                    "file_name": "mlt_o_rav_2017-01-04_lesson_boker_proxy",
                    "created_at": 1486666956,
                    "sha1": "4d4ad60c222220178a08560362a0b2c323f87a",
                    "size": 222
                }
            }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "status": "ok"
            }
        



## /operations/send

### Send Handler [POST]
Moves file from capture machine to other storage.


+ Request (application/json)



    + Body

            {
                "station": "10.66.1.120",
                "user": "operator@dev.com",
                "file_name": "mlt_o_rav_2017-01-04_lesson_boker_source",
                "created_at": 1484155956,
                "sha1": "4d4ad60c11738630178a08560362a0b2c323f87a",
                "dest": {
                    "file_name": "mlt_o_rav_2017-01-04_lesson_boker_dest",
                    "created_at": 1485555956,
                    "sha1": "4d4ad60c111110178a08560362a0b2c323f87a",
                    "size": 111222333
                }
            }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "status": "ok"
            }
        



## /operations/upload

### Upload Handler [POST]
Enabled file to be accessible from URL.


+ Request (application/json)



    + Body

            {
                "station": "10.66.1.120",
                "user": "operator@dev.com",
                "file_name": "mlt_o_rav_2017-01-04_lesson_boker_source",
                "created_at": 1484155956,
                "sha1": "4d4ad60c11738630178a08560362a0b2c323f87a",
                "size": 123123,
                "url": "http://some/url/file/was/uploaded/to",
                "duration": 9878
            }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "status": "ok"
            }
        



+ Request (application/json)



    + Body

            {
                "station": "10.66.1.120",
                "user": "operator@dev.com",
                "file_name": "mlt_o_rav_2017-01-04_lesson_boker_source",
                "created_at": 1484155956,
                "sha1": "4d4ad60c11738630178a08560362a0b2c323f87a",
                "size": 123123,
                "url": "http://some/url/file/was/uploaded/to",
                "duration": 9878,
                "existing": {
                    "file_name": "mlt_o_rav_2017-01-04_lesson_boker_dest",
                    "created_at": 1485555956,
                    "sha1": "4d4ad60c111110178a08560362a0b2c323f87a"
                }
            }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "status": "ok"
            }
        


